settings:
  token: 6168DB8D-DC58-4094-AF24-483278923590
  identityUrl: 
  callbackUrl:
  webhookUrl: http://host.docker.internal:5113
  selfUrl: http://host.docker.internal:5114
  validateToken: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: webhookclient
            authorization-grant-type: authorization_code
            scope: openid, profile
            client-secret: VRCq3Dwuoxhye942DZmWbmKn6qHbbfvE
            redirect-uri: ${settings.selfUrl}/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: ${oauthIssuerUrl}

oauthIssuerUrl: http://host.docker.internal:8095/realms/eshoponcontainers

logging:
  level:
    com.eshoponcontainers: DEBUG
