spring.profiles.active: dev
spring.application.name: webhooks-client

oauthIssuerUrl: http://host.docker.internal:8095/realms/eshoponcontainers

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.hibernate.type: TRACE