settings:
  token: 6168DB8D-DC58-4094-AF24-483278923590
  identityUrl: http://localhost:8095/realms/eshoponcontainers
  callbackUrl:
  webhookUrl: http://localhost:5113
  selfUrl: http://localhost:5114
  validateToken: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: webhookclient
            authorization-grant-type: authorization_code
            scope: openid, profile
            client-secret: TLqVSoKLJnbHAkehLb6RvmYR7jh9h1kx
            redirect-uri: ${settings.selfUrl}/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URL}



logging:
  level:
    com.eshoponcontainers: DEBUG
