replicaCount: 1
pathBase: /webshoppingapigw

image:
  repository: envoyproxy/envoy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.21.0"

service:
  type: ClusterIP
  port: 8082
  adminPort: 8083

resources: {}

env: {}

envoy:
  configPath: "/etc/envoy"

nodeSelector: {}

tolerations: []

affinity: {}
probes:
  liveness:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 15      
  readiness:
    httpGet:
      path: /ready
      port: 8080
  initialDelaySeconds: 5
  periodSeconds: 60
  
