replicaCount: 1

ingress:
  enabled: true

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "alpine"

service:
  type: ClusterIP
  port: 6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
