spring:
  datasource:    
    url: "jdbc:sqlserver://host.docker.internal:9133;databaseName=CatalogDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true;"
    username: sa
    password: Pass@word
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      naming.implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"

eventbus:
  host: "host.docker.internal"
  username:
  password:
  retryCount: 5
  subscriptionClientName: "Webhooks"


server:
  port: 5113

oauthIssuerUrl: http://host.docker.internal:8095/realms/eshoponcontainers