server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: log_collector
    static_configs:
      - targets:
          - testspringboot
        labels:
          job: job1
          __path__: /app_logs/**/*.log
    relabel_configs:
      - source_labels: [__path__]
        target_label: service
        regex: '/app_logs/([^/]+)/.*'
        replacement: '$1'
    pipeline_stages:
      - match:
          selector: '{job="log_collector"}'
          stages:
            - drop:
                expression: 'filename =~ ".*\.\d{4}-\d{2}-\d{2}\.log$"'