apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.inf.redis.basket.svc }}
  labels:
    app: {{ template "basket-data.name" . }}
    release: {{ .Release.Name }}
    chart: {{ template "basket-data.chart" . }}
    heritage: {{ .Release.Service }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redisport
      protocol: TCP
      name: redisport
  selector:
    app: {{ template "basket-data.name" . }}
    release: {{ .Release.Name }}
