{{- $name := include "keycloak.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-cm
  labels:
    app: {{ template "keycloak.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "keycloak.chart" . }}
data:
  eshoponcontainers-realm.json: |-
  {{ tpl( .Files.Get "files/eshoponcontainers-realm.json.tpl") . | indent 4 }}