apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "keycloak.fullname" . }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:  
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ template "keycloak.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:      
      labels:
        app: {{ template "keycloak.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: keycloak-config
          configMap:
            name: {{ template "keycloak.fullname" . }}-cm
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: keycloak
              containerPort: 8080
              protocol: TCP
          command: ["/opt/keycloak/bin/kc.sh", "-v", "start-dev", "--import-realm" ]            
          env:
          {{- if .Values.env.values }}
          {{- range .Values.env.values }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end -}}
          {{ end }}
          {{ if .Values.probes.liveness -}}
          livenessProbe:
          {{- toYaml .Values.probes.liveness | nindent 12 -}}
          {{ end }}
          {{ if .Values.probes.readiness -}}
          readinessProbe:
          {{- toYaml .Values.probes.readiness | nindent 12 -}}
          {{ end }}
          {{ if .Values.resources -}}
          resources:
          {{ toYaml .Values.resources | nindent 12 -}}
          {{ end -}}
          volumeMounts:
            - name: keycloak-config
              mountPath: "/opt/keycloak/data/import/" 
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end -}}