apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inf.issuer.svc }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: keycloak
      protocol: TCP
      name: keycloak
  selector:
    app: {{ template "keycloak.name" . }}
    release: {{ .Release.Name }}
