{{ $name:= include "ordering-backgroundtasks.fullname" . }}
{{ $cfgname:= printf "%s-%s" $name "cm" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $cfgname }}
  labels:
    app: {{ template "ordering-backgroundtasks.name" . }}
    chart: {{ template "ordering-backgroundtasks.chart" . }}
    release: {{ .Release.Name}}
    heritage: {{ .Release.Service }}
data:
  eventbus__host: {{ .Values.global.inf.eventbus.svc }}
  eventbus__username: {{ .Values.global.inf.eventbus.user }}
  eventbus__password: {{ .Values.global.inf.eventbus.pwd }}
  eventbus__retryCount: "{{ .Values.global.inf.eventbus.retryCount }}"
  ordering__dataSourceUrl: {{ .Values.global.inf.sql.ordering.datasourceUrl }}
  ordering__dataSourceUsername: {{ .Values.global.inf.sql.common.user }}
  ordering__dataSourcePassword: {{ .Values.global.inf.sql.common.pwd }}
  