{{ $name:= include "ordering-backgroundtasks.fullname" . }}
{{ $cfgname:= printf "%s-%s" $name "cm" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ordering-backgroundtasks.fullname" . }}
  labels:
    app: {{ include "ordering-backgroundtasks.name" . }}
    chart: {{ include "ordering-backgroundtasks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:  
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ include "ordering-backgroundtasks.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "ordering-backgroundtasks.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
          env:
            {{- range .Values.env.configmap }}
            - name: {{ .name }}
              valueFrom: 
                configMapKeyRef:
                  name: "{{ $cfgname }}"
                  key: {{ .key }}
            {{- end }}                 
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.fluentbit.enabled }}    
        - name: fluentbit-sidecar
          image: {{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
          imagePullPolicy: {{ .Values.fluentbit.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs/
            - name: fluentbit-config
              mountPath: /fluent-bit/etc/
          {{- end }}
      volumes:
        - name: log-volume
          emptyDir: {}
        {{- if .Values.fluentbit.enabled }}
        - name: fluentbit-config
          configMap:
            name: fluentbit-cm-orderingbackgroundtasks
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
