replicaCount: 1

image:
  repository: springeshop/webspa
  pullPolicy: Always
  tag: "latest"

ingress:
  enabled: true

service:
  type: ClusterIP
  port: 8081


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
