# {{ $name:= include "ordering-api.fullname" . }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "ordering-api.fullname" . }}-cm
  labels:
    app: {{ template "ordering-api.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "ordering-api.chart" . }}
data:
  eventbus__host: {{ .Values.eventbus.svc }}
  eventbus__username: {{ .Values.eventbus.user }}
  eventbus__password: {{ .Values.eventbus.pwd }}
  eventbus__retryCount: "{{ .Values.eventbus.retryCount }}"
  issuer__url: {{ .Values.issuer.url }}
  ordering__dataSourceUrl: {{ .Values.sql.datasource.url }}
  ordering__dataSourceUsername: {{ .Values.sql.common.user }}
  ordering__dataSourcePassword: {{ .Values.sql.common.pwd }}
  allowed__origins: "{{ .Values.global.app.allowedOrigins }}"
