# {{ $name:= include "ordering-api.fullname" . }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "ordering-api.fullname" . }}-cm
  labels:
    app: {{ template "ordering-api.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "ordering-api.chart" . }}
data:
  eventbus__host: {{ .Values.global.inf.eventbus.svc }}
  eventbus__username: {{ .Values.global.inf.eventbus.user }}
  eventbus__password: {{ .Values.global.inf.eventbus.pwd }}
  eventbus__retryCount: "{{ .Values.global.inf.eventbus.retryCount }}"  
  issuer__url: {{ .Values.global.inf.issuer.internalUrl }}
  ordering__dataSourceUrl: {{ .Values.global.inf.sql.ordering.datasourceUrl }}
  ordering__dataSourceUsername: {{ .Values.global.inf.sql.common.user }}
  ordering__dataSourcePassword: {{ .Values.global.inf.sql.common.pwd }}
