{{- $name:= include "ordering-api.fullname" . -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-{{ $name }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.vault.address | quote }}
    roleName: {{ .Values.vault.roleName | quote }}
    objects: |
      - objectName: DB_USER_NAME
        secretPath: {{ printf "%s/data/%s" .Values.vault.mountPath .Values.vault.dbSecretPath | quote }}
        secretKey: DB_USER_NAME
      - objectName: DB_PASSWORD
        secretPath: {{ printf "%s/data/%s" .Values.vault.mountPath .Values.vault.dbSecretPath | quote }}
        secretKey: DB_PASSWORD
      - objectName: EVENTBUS_USER_NAME
        secretPath: {{ printf "%s/data/%s" .Values.vault.mountPath .Values.vault.dbSecretPath | quote }}
        secretKey: EVENTBUS_USER_NAME
      - objectName: EVENTBUS_PASSWORD
        secretPath: {{ printf "%s/data/%s" .Values.vault.mountPath .Values.vault.dbSecretPath | quote }}
        secretKey: EVENTBUS_PASSWORD