apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.app.svc.ordering }}
  labels:
    app: {{ include "ordering-api.name" . }}
    chart: {{ include "ordering-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "ordering-api.name" . }}
    release: {{ .Release.Name }}
