{{ $name:= include "payment-api.name" . }}
{{ $cfgname:= printf "%s-%s" $name "cm" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $cfgname }}  
data:
  eventbus__host: {{ .Values.inf.eventbus.svc }}
  eventbus__username: {{ .Values.inf.eventbus.user }}
  eventbus__password: {{ .Values.inf.eventbus.pwd }}
  eventbus__retryCount: "{{ .Values.inf.eventbus.retryCount }}"