replicaCount: 1
pathBase: /ordering-api

image:
  repository: springeshop/orderingapi
  pullPolicy: IfNotPresent  
  tag: "latest"

service:
  type: ClusterIP
  port: 8086

env:
  configmap:
  - name: "eventbus.host"
    key: eventbus__host
  - name: "eventbus.username"
    key: eventbus__username
  - name: "eventbus.password"
    key: eventbus__password
  - name: "eventbus.retryCount"
    key: eventbus__retryCount  
  - name: "orderapi.datasource.url"
    key: ordering__dataSourceUrl
  - name: "orderapi.datasource.username"
    key: ordering__dataSourceUsername
  - name: "orderapi.datasource.password"
    key: ordering__dataSourcePassword
  - name: "issuer.url"
    key: issuer__url

  values:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: "/ordering-api"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80