spring:
  redis:
    host: host.docker.internal
    client-name: basketapi


basketdata.host: host.docker.internal
oauthIssuerUrl: http://host.docker.internal:8095/realms/eshoponcontainers

eventbus:
  host: "host.docker.internal"
  username:
  password:
  retryCount: 5
  subscriptionClientName: "Basket"

server.port: 9095

