spring:
  redis:
    host: ${basketdata.host}
    client-name: basketapi

eventbus:
  host: ${eventbus.host}
  username: ${eventbus.username}
  password: ${eventbus.password}
  retryCount: ${eventbus.retryCount}
  subscriptionClientName: "Basket"


oauthIssuerUrl: ${issuer.url}
allowedCorsOrigin: ${webspa.allowedCorsOrigin}

logging:
  level:
    com.eshoponcontainers: DEBUG

#enable management endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
