spring:
  redis:
    host: host.docker.internal
    client-name: basketapi

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8095/realms/eshoponcontainers

basketdata.host: host.docker.internal
oauthIssuerUrl: http://host.docker.internal:8095/realms/eshoponcontainers

eventbus:
  host: "host.docker.internal"
  username:
  password:
  retryCount: 5

server.port: 9095

