spring:
  redis:
    host: ${basketdata.host}
    client-name: basketapi

eventbus:
  host: ${eventbus.host}
  username: ${eventbus.username}
  password: ${eventbus.password}
  retryCount: ${eventbus.retryCount}
  subscriptionClientName: "Basket"

oauthIssuerUrl: http://${issuer.host}:${issuer.port}/realms/eshoponcontainers

logging:
  level:
    com.eshoponcontainers: DEBUG
