spring:
  redis:
    host: ${basketdata.host}
    client-name: basketapi

eventbus:
  host: "eventbus"
  username:
  password:
  retryCount: 5
  subscriptionClientName: "Basket"

oauthIssuerUrl: http://keycloak:8080/realms/eshoponcontainers

logging:
  level:
    com.eshoponcontainers: DEBUG
