{{- $name:= include "catalog-api.fullname" . -}}
{{- $webshoppingapigw:= include "url-of" (list .Values.ingress.webshoppingapigw .) -}}
{{- $protocol:= include "protocol" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "cfg-{{$name}}"
  labels:
    app: {{ include "catalog-api.name" . }}
    chart: {{ include "catalog-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  catalog__picBaseUrl: {{ .Values.picBaseUrl }}
  catalog__dataSourceUrl: {{ .Values.sql.datasource.url }}
  catalog__dataSourceUsername: {{ .Values.sql.common.user }}
  catalog__dataSourcePassword: {{ .Values.sql.common.pwd }}
  eventbus__host: {{ .Values.eventbus.svc }}
  eventbus__username: {{ .Values.eventbus.user }}
  eventbus__password: {{ .Values.eventbus.pwd }}
  eventbus__retryCount: "{{ .Values.eventbus.retryCount }}"
  allowed__origins: "{{ .Values.allowedOrigins }}"
