apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "catalog-api.fullname" .}}
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ .Chart.Name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.averageCPUUtilizationPercent }}