global:
  inf:
    tls:
      enabled: false
      issuer: ""
    sql:
      host: springeshop-sql-data
      common:
        user: sa
        pwd: Pass@word
        pid: Developer
        TrustServerCertificate: true
      catalog:
        datasourceUrl: "jdbc:sqlserver://sql-data:9433;databaseName=CatalogDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true;"
        db: CatalogDb
      ordering:
        db: OrderDb
        datasourceUrl: "jdbc:sqlserver://sql-data:9433;databaseName=OrderDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true;"
    mongo:
      host: 
    redis:
      basket:
        host: redis://basket-data:6379
        svc: basket-data
        constr: basket-data
      keystore:
        svc: keystore-data
        constr: keystore-data
    eventbus:
      svc: rabbitmq
      user: guest
      pwd: guest
      retryCount: "5"
    issuer:
      svc: keycloak
      port: "8080"
      servicePort: "8085"
      url: "http://localhost/keycloak/realms/eshoponcontainers"
      internalUrl: "http://keycloak:8085/keycloak/realms/eshoponcontainers"
    k8s:
      dns: "localhost"
      local: false