replicaCount: 1
pathBase: /basket-api

image:
  repository: harshaghanta/basketapi
  pullPolicy: IfNotPresent  
  tag: "latest"

fluentbit:
  enabled: false
  indexName: basket-api-logs
  logPath: /app/logs
  image:
    repository: fluent/fluent-bit
    tag: 1.8.3
    pullPolicy: IfNotPresent
  elasticsearch:
    host: "elasticsearch-master.logging.svc.cluster.local"
    port: 9200
    user: "elastic"
    password: "elastic"

ingress:
  enabled: true

service:
  type: ClusterIP
  port: "8084"
  name: basket-api

eventbus:
  svc: rabbitmq
  user: "guest"
  pwd: "guest"
  retryCount: "5"

issuer:
  svc: keycloak
  port: 9999
  internalIssuerUrl: http://keycloak:8085/keycloak/realms/eshoponcontainers

allowedOrigins: ""


basketdata:
  uri: redis://basket-data:6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  urls:
  configmap:
    - name: "eventbus.host"
      key: eventbus__host
    - name: "eventbus.username"
      key: eventbus__username
    - name: "eventbus.password"
      key: eventbus__password
    - name: "eventbus.retryCount"
      key: eventbus__retryCount
    # - name: "issuer.host"
    #   key: issuer__host
    # - name: "issuer.port"
    #   key: issuer__port
    - name: "basketdata.host"
      key: basketdata__host
    # - name: "issuer.url"
    #   key: issuer__url
    - name: "webspa.allowedCorsOrigin"
      key: allowed__origins
    
  
  values:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: "/basket-api"
    - name: SECRETS_PATH
      value: "/vault/secrets"
    - name: EVENTBUS_HOST
      value: "rabbitmq"
    - name: EVENTBUS_SUBSCRIPTION_CLIENT_NAME
      value: Basket
    - name: ALLOWED_ORIGINS
      value: "eshop.ghantas.com"
    - name: ALLOWED_HEADERS
      value: "*"
    - name: ALLOWED_METHODS
      value: "*"
    - name: ISSUER_URL
      value: "http://keycloak:8085/keycloak/realms/eshoponcontainers"
    - name: REDIS_HOST_NAME
      value: "basket-data"
    - name: REDIS_HOST_PORT
      value: "6379"
    - name: REDIS_TIMEOUT
      value: "5000"
  

probes:
  liveness:
    path: /basket-api/actuator/health/liveness
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 15
    port: 8080
  readiness:
    path: /basket-api/actuator/health/readiness
    timeoutSeconds: 5
    initialDelaySeconds: 15
    periodSeconds: 15
    port: 8080

