replicaCount: 1
pathBase: /basket-api

image:
  repository: harshaghanta/basketapi
  pullPolicy: IfNotPresent  
  tag: "latest"

fluentbit:
  enabled: false
  indexName: basket-api-logs
  logPath: /app/logs
  image:
    repository: fluent/fluent-bit
    tag: 1.8.3
    pullPolicy: IfNotPresent
  elasticsearch:
    host: "elasticsearch-master.logging.svc.cluster.local"
    port: 9200
    user: "elastic"
    password: "elastic"

ingress:
  enabled: true

service:
  type: ClusterIP
  port: "8084"
  name: basket-api

eventbus:
  svc: rabbitmq
  user: "guest"
  pwd: "guest"
  retryCount: "5"

issuer:
  svc: keycloak
  port: 9999
  internalIssuerUrl: http://keycloak:8085/realms/eshoponcontainers

allowedOrigins: ""


basketdata:
  uri: redis://basket-data:6379

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  urls:
  configmap:
    - name: "eventbus.host"
      key: eventbus__host
    - name: "eventbus.username"
      key: eventbus__username
    - name: "eventbus.password"
      key: eventbus__password
    - name: "eventbus.retryCount"
      key: eventbus__retryCount
    - name: "issuer.host"
      key: issuer__host
    - name: "issuer.port"
      key: issuer__port
    - name: "basketdata.host"
      key: basketdata__host
    - name: "issuer.url"
      key: issuer__url
    - name: "webspa.allowedCorsOrigin"
      key: allowed__origins
    
  
  values:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: "/basket-api"
  

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80

