apiVersion: v1
entries:
  catalog-api:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-07-22T22:34:03.4658991+05:30"
    description: A Helm chart for Kubernetes
    digest: b375ef7323a0646c90cdffb94776645c8cc8517a68b5262675c50546e7fd4233
    name: catalog-api
    type: application
    urls:
    - catalog-api-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-07-22T22:34:03.4602078+05:30"
    description: A Helm chart for Kubernetes
    digest: ba294fc0af2eba86ebff10e30cdb30ea39cbacadd5278729eb395cf683f8f232
    name: catalog-api
    type: application
    urls:
    - catalog-api-0.1.5.tgz
    version: 0.1.5
  sql-data:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-07-22T22:34:03.4670206+05:30"
    description: A Helm chart for Kubernetes
    digest: af49b9ea370b96f473e15b24d6df3a4bfc823e393560643ddea19b65bd9bf646
    name: sql-data
    type: application
    urls:
    - sql-data-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-07-22T22:34:03.4664958+05:30"
    description: A Helm chart for Kubernetes
    digest: 35bac409cf78cf0a40882e9ea2860fa54d1ce6baa36c462a01ca164ee6b8adef
    name: sql-data
    type: application
    urls:
    - sql-data-0.1.0.tgz
    version: 0.1.0
generated: "2025-07-22T22:34:03.4602078+05:30"
