config-data:
  identityUrl: ${webspa.identityUrl}
  basketUrl: ${webspa.basketUrl}
  marketingUrl: null
  purchaseUrl: ${webspa.purchaseUrl}
  signalrHubUrl: ${webspa.signalrHubUrl}
  activateCampaignDetailFunction: "False"
  useCustomizationData: true
