spring:
  application:
    name: webspa
  profiles:
    active:
    - dev

#enable management endpoints
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server: 
            requests: true
  tracing:
    sampling:
      probability: 1.0
        
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

config-data:
  identityUrl: ${webspa.identityUrl}
  basketUrl: ${webspa.basketUrl}
  marketingUrl: null
  purchaseUrl: ${webspa.purchaseUrl}
  signalrHubUrl: ${webspa.signalrHubUrl}
  activateCampaignDetailFunction: "False"
  useCustomizationData: true


