{{- $name := include "apigwws.fullname" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}
{{- $envoycfgname := printf "%s-%s" "envoy" $name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apigwws.fullname" . }}
  labels:
    app: {{ template "apigwws.name" . }}
    release: {{ .Release.Name }}
    chart: {{ template "apigwws.chart" . }}
    heritage: {{ .Release.Service }}
spec:  
  replicas: {{ .Values.replicaCount }}
  
  selector:
    matchLabels:
      app: {{ template "apigwws.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:      
      labels:
        app: {{ template "apigwws.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ $envoycfgname }}
            items:
            - key: envoy.yaml
              path: envoy.yaml
        - name : logpath
          emtpyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ template "fqdn-image" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: "/etc/envoy/"
            - name: logpath
              mountPath: "/var/log/envoy/"
          env:
            # - name: PATH_BASE
            #   value: "{{ include "pathBase" . }}"
            {{- if .Values.env.values -}}
            {{- range .Values.env.values }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end -}}
            {{- end -}}
            {{- if .Values.env.configmap -}}
            {{- range .Values.env.configmap -}}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $cfgname }}
                  key: {{ .key }}
            {{- end -}}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 8001
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
