{{- $serviceName :=  .Values.service.name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "apigwws.fullname" . }}
  labels:
    app: {{ template "apigwws.name" . }}
    chart: {{ template "apigwws.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # removing the / before the $2 is not redirecting correctly
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:    
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /webshoppingapigw(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service: 
                name: "{{ $serviceName }}"
                port:
                  number: {{ .Values.service.port }}