metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    namespace: eshop
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: rabbitmq
    repoURL: https://harshaghanta.github.io/springboot-eshopOnContainers/
    targetRevision: 0.1.1
