minReplicas: 2
maxReplicas: 5
averageCPUUtilizationPercent: 10
maxSurge: 1

clusterName: eshop-aks

allowedOrigins: ""
picBaseUrl: "https://harshaghanta.github.io/springboot-eshopOnContainers/resources/catalog/images/[0]"

image:
  repository: harshaghanta/catalogapi
  pullPolicy: Always  
  tag: "latest"

fluentbit:
  enabled: false
  indexName: catalog-api-logs
  logPath: /app/logs
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
  image:
    repository: fluent/fluent-bit
    tag: 1.8.3
    pullPolicy: IfNotPresent
  elasticsearch:
    host: "elasticsearch-master.logging.svc.cluster.local"
    port: 9200
    user: "elastic"
    password: "elastic"
  


registry:
  server: ""

tls:
  enabled: false

k8s:
  dns: "localhost"

sql:
  common:
    user: "sa"
    pwd: "P@ssw0rd"
  datasource:
    url: "jdbc:sqlserver://sql-data:1433;databaseName=CatalogDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true;"

eventbus:
  svc: rabbitmq
  user: "guest"
  pwd: "guest"
  retryCount: "5"

ingress:
  webshoppingapigw: webshoppingapigw

service:
  type: ClusterIP
  port: 8081
  name: catalog-api

resources:
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  configmap:
    - name: "catalog.datasource.url"
      key: catalog__dataSourceUrl
    - name: "catalog.picBaseUrl"
      key: catalog__picBaseUrl
    # - name: EventBusConnection
    #   key: all__EventBusConnection
    - name: "catalog.datasource.username"
      key: catalog__dataSourceUsername
    - name: "catalog.datasource.password"
      key: catalog__dataSourcePassword
    - name: "eventbus.host"
      key: eventbus__host
    - name: "eventbus.username"
      key: eventbus__username
    - name: "eventbus.password"
      key: eventbus__password
    - name: "eventbus.retryCount"
      key: eventbus__retryCount
    - name: "webspa.allowedCorsOrigin"
      key: allowed__origins

  values:
    - name: SERVER_SERVLET_CONTEXT_PATH
      value: "/catalog-api"
  probes:
    liveness:
      path: /catalog-api/actuator/health/liveness
      initialDelaySeconds: 30
      timeoutSeconds: 5
      periodSeconds: 15
      port: 8080
    readiness:
      path: /catalog-api/actuator/health/readiness
      timeoutSeconds: 5
      initialDelaySeconds: 90
      periodSeconds: 15
      port: 8080