apiVersion: v2
name: eshop
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: apigwws
    version: 0.1.0
    repository: "file://charts/apigwws"
  - name: basket-api
    version: 0.1.0
    repository: "file://charts/basket-api"
  - name: basket-data
    version: 0.1.0
    repository: "file://charts/basket-data"
  - name: catalog-api
    version: 0.1.0
    repository: "file://charts/catalog-api"
  - name: keycloak
    version: 0.1.0
    repository: "file://charts/keycloak"
  - name: ordering-api
    version: 0.1.0
    repository: "file://charts/ordering-api"
  - name: ordering-backgroundtasks
    version: 0.1.0
    repository: "file://charts/ordering-backgroundtasks"
  - name: payment-api
    version: 0.1.0
    repository: "file://charts/payment-api"
  - name: rabbitmq
    version: 0.1.0
    repository: "file://charts/rabbitmq"
  - name: sql-data
    version: 0.1.0
    repository: "file://charts/sql-data"
  - name: webspa
    version: 0.1.0
    repository: "file://charts/webspa"