apigwws:
  replicaCount: 1
  pathBase: /webshoppingapigw
  fullnameOverride: webshoppingapigw

  ingress:
    enabled: true

  image:
    repository: envoyproxy/envoy
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.21.0"

  service:
    type: ClusterIP
    port: 8082
    adminPort: 8083

  resources: {}

  env: {}

  envoy:
    configPath: "/etc/envoy"

  nodeSelector: {}

  tolerations: []

  affinity: {}
  probes:
    liveness:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 15      
    readiness:
      httpGet:
        path: /ready
        port: 8080
    initialDelaySeconds: 5
    periodSeconds: 60

basket-api:  
  replicaCount: 1
  pathBase: /basket-api
  fullnameOverride: basket-api

  ingress:
    enabled: true

  image:
    repository: harshaghanta/basketapi
    pullPolicy: IfNotPresent  
    tag: "latest"

  service:
    type: ClusterIP
    port: "8084"


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env:
    urls:
    configmap:
      - name: "eventbus.host"
        key: eventbus__host
      - name: "eventbus.username"
        key: eventbus__username
      - name: "eventbus.password"
        key: eventbus__password
      - name: "eventbus.retryCount"
        key: eventbus__retryCount
      - name: "issuer.host"
        key: issuer__host
      - name: "issuer.port"
        key: issuer__port
      - name: "basketdata.host"
        key: basketdata__host
      - name: "issuer.url"
        key: issuer__url
      - name: "webspa.allowedCorsOrigin"
        key: allowed__origins
    
    values:
      - name: SERVER_SERVLET_CONTEXT_PATH
        value: "/basket-api"
    

  probes:
    liveness:
      path: /liveness
      initialDelaySeconds: 10
      periodSeconds: 15
      port: 80
    readiness:
      path: /hc
      timeoutSeconds: 5
      initialDelaySeconds: 90
      periodSeconds: 60
      port: 80

basket-data:
  replicaCount: 1
  fullnameOverride: basket-data
  ingress:
    enabled: true

  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: "alpine"

  service:
    type: ClusterIP
    port: 6379

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

catalog-api:
  replicaCount: 1
  clusterName: eshop-aks
  fullnameOverride: catalog-api

  image:
    repository: harshaghanta/catalogapi
    pullPolicy: IfNotPresent  
    tag: "latest"


  service:
    type: ClusterIP
    port: 8081

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env:
    configmap:
      - name: "catalog.datasource.url"
        key: catalog__dataSourceUrl
      - name: "catalog.picBaseUrl"
        key: catalog__picBaseUrl
      # - name: EventBusConnection
      #   key: all__EventBusConnection
      - name: "catalog.datasource.username"
        key: catalog__dataSourceUsername
      - name: "catalog.datasource.password"
        key: catalog__dataSourcePassword
      - name: "eventbus.host"
        key: eventbus__host
      - name: "eventbus.username"
        key: eventbus__username
      - name: "eventbus.password"
        key: eventbus__password
      - name: "eventbus.retryCount"
        key: eventbus__retryCount
      - name: "webspa.allowedCorsOrigin"
        key: allowed__origins

    values:
      - name: SERVER_SERVLET_CONTEXT_PATH
        value: "/catalog-api"
    probes:
      liveness:
        path: /liveness
        initialDelaySeconds: 10
        periodSeconds: 15
        port: 80
      readiness:
        path: /hc
        timeoutSeconds: 5
        intialDelaySeconds: 90
        periodSeconds: 60
        port: 80

keycloak:
  replicaCount: 1
  fullnameOverride: keycloak

  image:
    repository: quay.io/keycloak/keycloak
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service:
    type: ClusterIP
    port: 8085

  env:
    values:
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      - name: DB_VENDOR
        value: h2    
      - name: KC_HEALTH_ENABLED
        value: true
      - name: KEYCLOAK_FRONTEND_URL
        value: http://localhost/keycloak
      - name: KC_HTTP_RELATIVE_PATH
        value: /keycloak
      - name: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - name: KEYCLOAK_LOGGERS
        value: org.keycloak.events
      # - name: KEYCLOAK_HTTP_RELATIVE_PATH
      #   value: /keycloak
      # - name: PROXY_ADDRESS_FORWARDING
      #   value: "true"
      


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  probes:
    liveness: {}
      # httpGet:
      #   path: /ready
      #   port: 8080
      # initialDelaySeconds: 5
      # periodSeconds: 15
      
    readiness: {}
      # httpGet:  
      #   path: /ready
      #   port: 8080
      # initialDelaySeconds: 5
      # periodSeconds: 60

ordering-api:
  replicaCount: 1
  pathBase: /ordering-api
  fullnameOverride: ordering-api

  image:
    repository: harshaghanta/orderingapi
    pullPolicy: IfNotPresent  
    tag: "latest"

  service:
    type: ClusterIP
    port: 8086

  env:
    configmap:
    - name: "eventbus.host"
      key: eventbus__host
    - name: "eventbus.username"
      key: eventbus__username
    - name: "eventbus.password"
      key: eventbus__password
    - name: "eventbus.retryCount"
      key: eventbus__retryCount  
    - name: "orderapi.datasource.url"
      key: ordering__dataSourceUrl
    - name: "orderapi.datasource.username"
      key: ordering__dataSourceUsername
    - name: "orderapi.datasource.password"
      key: ordering__dataSourcePassword
    - name: "issuer.url"
      key: issuer__url
    - name: "webspa.allowedCorsOrigin"
      key: allowed__origins

    values:
      - name: SERVER_SERVLET_CONTEXT_PATH
        value: "/ordering-api"

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  probes:
    liveness:
      path: /liveness
      initialDelaySeconds: 10
      periodSeconds: 15
      port: 80
    readiness:
      path: /hc
      timeoutSeconds: 5
      initialDelaySeconds: 90
      periodSeconds: 60
      port: 80

ordering-backgroundtasks:
  replicaCount: 1
  fullnameOverride: ordering-backgroundtasks

  image:
    repository: harshaghanta/orderingbackgroundtasks
    pullPolicy: IfNotPresent
    tag: "latest"

  env:
    configmap:
    - name: "eventbus.host"
      key: eventbus__host
    - name: "eventbus.username"
      key: eventbus__username
    - name: "eventbus.password"
      key: eventbus__password  
    - name: "orderapi.datasource.url"
      key: ordering__dataSourceUrl
    - name: "orderapi.datasource.username"
      key: ordering__dataSourceUsername
    - name: "orderapi.datasource.password"
      key: ordering__dataSourcePassword



  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  probes:
    liveness:
      path: /liveness
      initialDelaySeconds: 10
      periodSeconds: 15
      port: 80
    readiness:
      path: /hc
      timeoutSeconds: 5
      initialDelaySeconds: 90
      periodSeconds: 60
      port: 80

payment-api:
  replicaCount: 1
  fullnameOverride: payment-api

  image:
    repository: harshaghanta/paymentapi
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

  service:
    type: ClusterIP
    port: 8087

  env:
    configmap:
    - name: "eventbus.host"
      key: eventbus__host
    - name: "eventbus.username"
      key: eventbus__username
    - name: "eventbus.password"
      key: eventbus__password
    - name: "eventbus.retryCount"
      key: eventbus__retryCount


  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi


  nodeSelector: {}

  tolerations: []

  affinity: {}

rabbitmq:
  replicaCount: 1
  fullnameOverride: rabbitmq

  image:
    repository: rabbitmq
    pullPolicy: IfNotPresent  
    tag: "3-management-alpine"

  service:
    type: ClusterIP
    internalPort: 5672
    externalPort: 5672

  resources:
    # requests:
    #   memory: "64Mi"
    #   cpu: "250m"
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"

  nodeSelector: {}

  tolerations: []

  affinity: {}

sql-data:
  replicaCount: 1
  fullnameOverride: sql-data

  image:
    repository: harshaghanta/db
    pullPolicy: Never
    tag: "latest"

  service:
    type: ClusterIP
    internalPort: 1433
    externalPort: 9433
    name: sql-service
    
  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

webspa:
  replicaCount: 1
  fullnameOverride: webspa

  image:
    repository: harshaghanta/webspa
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 8081


  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
