replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

env:
  values:
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: DB_VENDOR
      value: h2    
    - name: KC_HEALTH_ENABLED
      value: true
    


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
