replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ingress:
  enabled: true

service:
  type: ClusterIP
  port: 8085
  name: keycloak

env:
  values:
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: DB_VENDOR
      value: h2    
    - name: KC_HEALTH_ENABLED
      value: true
    - name: KEYCLOAK_FRONTEND_URL
      value: auth.ghantas.com
    - name: KC_HTTP_RELATIVE_PATH
      value: /keycloak
    - name: KEYCLOAK_LOGLEVEL
      value: DEBUG
    - name: KEYCLOAK_LOGGERS
      value: org.keycloak.events
    # - name: KEYCLOAK_HTTP_RELATIVE_PATH
    #   value: /keycloak
    # - name: PROXY_ADDRESS_FORWARDING
    #   value: "true"
    


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

probes:
  liveness: {}
    # httpGet:
    #   path: /ready
    #   port: 8080
    # initialDelaySeconds: 5
    # periodSeconds: 15
    
  readiness: {}
    # httpGet:  
    #   path: /ready
    #   port: 8080
    # initialDelaySeconds: 5
    # periodSeconds: 60
    
