apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice
spec:
  hosts:
  - eshop.ghantas.com
  gateways:
  - eshop-gateway
  http:
  - name: catalog-service-short-routing
    match:
    - uri:
        regex: /webshoppingapigw/c/(.*)
    rewrite:
      uriRegexRewrite:
        match: "/webshoppingapigw/c/(.*)"
        rewrite: /catalog-api/\1
    route:
    - destination:
        host: catalog-api.eshop.svc.cluster.local
        subset: catalog-service-subset
  - name: catalog-service-long-routing
    match:
    - uri:
        regex: /webshoppingapigw/catalog-api/(.*)
    rewrite:
      uriRegexRewrite:
        match: "/webshoppingapigw/catalog-api/(.*)"
        rewrite: /catalog-api/\1
    route:
    - destination:
        host: catalog-api.eshop.svc.cluster.local
        subset: catalog-service-subset

  - name: webspa-routing
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: webspa.eshop.svc.cluster.local
        subset: webspa-service-subset
  - name: basket-service-short-routing
    match:
    - uri:
        regex: /webshoppingapigw/b/(.*)
    rewrite:
      uriRegexRewrite:
        match: "/webshoppingapigw/b/(.*)"
        rewrite: /basket-api/\1
    route:
    - destination:
        host: basket-api.eshop.svc.cluster.local
        subset: basket-service-subset
  - name: basket-service-long-routing
    match:
    - uri:
        regex: /webshoppingapigw/basket-api/(.*)
    rewrite:
      uriRegexRewrite:
        match: "/webshoppingapigw/basket-api/(.*)"
        rewrite: /basket-api/\1
    route:
    - destination:
        host: basket-api.eshop.svc.cluster.local
        subset: basket-service-subset

  - name: ordering-service-short-routing
    match:
    - uri:
        regex: /webshoppingapigw/o/(.*)
    rewrite:
      uriRegexRewrite:
        match: "/webshoppingapigw/o/(.*)"
        rewrite: /ordering-api/\1
    route:
    - destination:
        host: ordering-api.eshop.svc.cluster.local
        subset: ordering-service-subset
  - name: ordering-service-long-routing
    match:
    - uri:
        regex: /webshoppingapigw/ordering-api/(.*)
    rewrite:
      uriRegexRewrite:
        match: "/webshoppingapigw/ordering-api/(.*)"
        rewrite: /ordering-api/\1
    route:
    - destination:
        host: ordering-api.eshop.svc.cluster.local
        subset: ordering-service-subset


        
