{{- $protocol := include "protocol" . -}}
{{- $webshoppingapigw := include "url-of" (list .Values.global.app.ingress.entries.webshoppingapigw .) -}}
{{- $keycloak:= include "url-of" (list .Values.global.app.ingress.entries.keycloak .) -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "cfg-{{ include "webspa.fullname" . }}"
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yml: |
    config-data:
      identityUrl: {{$protocol}}://{{$keycloak}}/realms/eshoponcontainers/protocol
      basketUrl: "http://host.docker.internal:8083"
      marketingUrl: null
      purchaseUrl: {{$protocol}}://{{$webshoppingapigw}}
      signalrHubUrl: "http://host.docker.internal:8090"
      activateCampaignDetailFunction: "False"
      useCustomizationData: true