{{- $protocol := include "protocol" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "cfg-{{ include "webspa.fullname" . }}"
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yml: |
    config-data:
      identityUrl: {{$protocol}}://{{ .Values.authDomainName}}/keycloak/realms/eshoponcontainers/protocol
      basketUrl: {{$protocol}}://{{ .Values.domainName}}/webshoppingapigw
      marketingUrl: null
      purchaseUrl: {{$protocol}}://{{ .Values.domainName}}/webshoppingapigw
      signalrHubUrl: {{$protocol}}://{{ .Values.domainName}}/webshoppingapigw
      activateCampaignDetailFunction: "False"
      useCustomizationData: true