{{- $protocol := include "protocol" . -}}
{{- $webshoppingapigw := include "url-of" (list .Values.app.ingress.entries.webshoppingapigw .) -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "cfg-{{ include "webspa.fullname" . }}"
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yml: |
    config-data:
      identityUrl: "http://localhost:8080/realms/eshoponcontainers/protocol"
      basketUrl: "http://host.docker.internal:8083"
      marketingUrl: null
      purchaseUrl: "http://localhost/webshoppingapigw"
      signalrHubUrl: "http://host.docker.internal:8090"
      activateCampaignDetailFunction: "False"
      useCustomizationData: true