apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webspa.fullname" . }}
  labels:
    app: {{ include "webspa.name" . }}
    chart: {{ include "webspa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:  
  replicas: {{ .Values.replicaCount }}  
  selector:
    matchLabels:
      app: {{ template "webspa.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:      
      labels:
        app: {{ template "webspa.name" . }}
        release: {{ .Release.Name }}
    spec:     
      containers:
        - name: {{ .Chart.Name }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/application.yml
              subPath: application.yml
            - name: log-volume
              mountPath: /app/logs
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.fluentbit.enabled }}
        - name: fluentbit-sidecar
          image: {{ .Values.fluentbit.image.repository }}:{{ .Values.fluentbit.image.tag }}
          imagePullPolicy: {{ .Values.fluentbit.image.pullPolicy }}
          securityContext:
            privileged: true          
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs/          
            - name: fluentbit-config
              mountPath: /fluent-bit/etc/
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: "cfg-{{ include "webspa.fullname" . }}"
        - name: log-volume
          emptyDir: {}
        {{- if .Values.fluentbit.enabled }}
        - name: fluentbit-config
          configMap:
            name: fluentbit-cm-webspa
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
