{{ $name:= include "webspa.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ $name }}
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  # Works directly with out annotations for the webspa, when other ingress rules doesnt exist
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:    
    - host: {{ .Values.domainName }}
      http:
        paths:
        - path: /webshoppingapigw(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service: 
              name: {{ .Values.service.apigwname }}
              port:
                number: {{ .Values.service.apigwport }}
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: {{ include "webspa.fullname" . }}
              port:
                number: {{ .Values.service.port }}