global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: 'otel_java_agent'
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - catalog-api:9464
        labels:
          application: catalog-api
      - targets:
          - basket-api:9464
        labels:
          application: basket-api
      - targets:
          - ordering-api:9464
        labels:
          application: ordering-api
      - targets:
          - ordering-backgroundtasks:9464
        labels:
          application: ordering-backgroundtasks
      - targets:
          - webspa:9464
        labels:
          application: webspa
      - targets:
          - webhooks-api:9464
        labels:
          application: webhooks-api
      - targets:
          - webhooks-client:9464
        labels:
          application: webhooks-client
      - targets:
          - payment-api:9464
        labels:
          application: payment-api
  - job_name: 'otel_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - basket-api:8080
        labels:
          application: basket-api
