global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: 'otel_java_agent'
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - catalog-api:9464
        labels:
          application: catalog-api
      - targets:
          - basket-api:9464
        labels:
          application: basket-api
      - targets:
          - ordering-api:9464
        labels:
          application: ordering-api
      - targets:
          - ordering-backgroundtasks:9464
        labels:
          application: ordering-backgroundtasks
      - targets:
          - webspa:9464
        labels:
          application: webspa
      - targets:
          - webhooks-api:9464
        labels:
          application: webhooks-api
      - targets:
          - webhooks-client:9464
        labels:
          application: webhooks-client
      - targets:
          - payment-api:9464
        labels:
          application: payment-api

  - job_name: 'basketapi_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /basket-api/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - basket-api:8080
        labels:
          application: basket-api

  - job_name: 'catalogapi_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /catalog-api/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - catalog-api:8080
        labels:
          application: catalog-api

  - job_name: 'orderingapi_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /ordering-api/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - ordering-api:8080
        labels:
          application: ordering-api

  - job_name: 'orderingbackground_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /ordering-backgroundtasks/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - ordering-backgroundtasks:8080
        labels:
          application: ordering-backgroundtasks

  - job_name: 'webspa_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /webspa/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - webspa:8080
        labels:
          application: webspa

  - job_name: 'webhooks-api_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /webhooks-api/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - webhooks-api:8080
        labels:
          application: webhooks-api

  - job_name: 'webhooks-client_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /webhooks-client/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - webhooks-client:8080
        labels:
          application: webhooks-client


  - job_name: 'payment-api_prometheus_exporter'
    honor_timestamps: true
    metrics_path: /payment-api/actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - payment-api:8080
        labels:
          application: payment-api

  # - job_name: 'testspringboot_prometheus_exporter'
  #   honor_timestamps: true
  #   metrics_path: /actuator/prometheus
  #   scheme: http
  #   static_configs:
  #     - targets:
  #         - testspringboot:8080
  #       labels:
  #         application: testspringboot
