version: '3.4'
services:
  catalog-api:    
    build:
      context: .
      dockerfile: Services/catalogapi/Dockerfile
    env_file:
    - .env
    depends_on:
    - db
    - eventbus
    ports:
    - 8081:8080
    networks:
    - simpbridgenetwork
  basket-api:
    build:
      context: .
      dockerfile: Services/basketapi/Dockerfile
    env_file:
    - .env
    depends_on:
    - basketdata
    - eventbus
    ports:
    - 8083:8080
    networks:
    - simpbridgenetwork

  db:
    build:
      context: .
      dockerfile: "DBSetup/Dockerfile"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    ports:
    - 9133:1433
    networks:
    - simpbridgenetwork
  eventbus:
    image: rabbitmq:3-management-alpine
    container_name: eventbus
    networks:
    - simpbridgenetwork
    ports:
    - 5672:5672 
    - 15672:15672
  ordering-api:    
    build:
      context: .
      dockerfile: Services/Ordering/orderapi/Dockerfile
    env_file:
    - .env
    depends_on:
    - db
    - eventbus
    ports:
    - 8082:8080
    networks:
    - simpbridgenetwork
  ordering-backgroundtasks:
    build:
      context: .
      dockerfile: Services/Ordering/ordering-backgroundtasks/Dockerfile
    env_file:
    - .env
    depends_on:
    - db
    - eventbus
    networks:
      - simpbridgenetwork
  webspa:
    build:
      context: .
      dockerfile: Web/WebSpa/server/Dockerfile  
    ports:
    - 8080:8080
    networks:
    - simpbridgenetwork

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin 
    - DB_VENDOR=h2
    volumes:
      - ./Keycloak:/opt/keycloak/data/import
    command: -v start-dev --import-realm
    ports:
    - 8095:8080
    networks:
    - simpbridgenetwork
  
  webshoppingapigw:
    image: envoyproxy/envoy:v1.11.1
    networks:
    - simpbridgenetwork

  basketdata:
    image: redis:alpine
    networks:
    - simpbridgenetwork
  
  webhooks-api:    
    build:
      context: .
      dockerfile: Services/Webhooks/webhooks-api/Dockerfile
    env_file:
    - .env
    depends_on:
    - db
    - eventbus
    ports:
    - 5113:8080
    networks:
    - simpbridgenetwork
  webhooks-client:    
    build:
      context: .
      dockerfile: Services/Webhooks/webhooks-client/Dockerfile
    env_file:
    - .env
    ports:
    - 5114:8080
    networks:
    - simpbridgenetwork
  payment-api:
    build:
      context: .
      dockerfile: Services/Payment/paymentapi/Dockerfile
    env_file:
    - .env
    ports:
    - 5108:8080
    networks:
    - simpbridgenetwork

networks:
  simpbridgenetwork:
