version: '3.4'
services:
  catalog-api:    
    build:
      context: .
      dockerfile: Services/catalogapi/Dockerfile
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    ports:
    - 8081:8080
    volumes:
      - applog_volume:/app/logs
    networks:
    - simpbridgenetwork
  basket-api:
    build:
      context: .
      dockerfile: Services/basketapi/Dockerfile
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      basketdata:
        condition: service_started
    ports:
    - 8083:8080
    networks:
    - simpbridgenetwork

  db:
    build:
      context: .
      dockerfile: "DBSetup/Dockerfile"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    ports:
    - 9133:1433
    networks:
    - simpbridgenetwork
  eventbus:
    image: rabbitmq:3-management-alpine
    container_name: eventbus
    networks:
    - simpbridgenetwork
    ports:
    - 5672:5672 
    - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  ordering-api:    
    build:
      context: .
      dockerfile: Services/Ordering/orderapi/Dockerfile
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    ports:
    - 8082:8080
    networks:
    - simpbridgenetwork
  ordering-backgroundtasks:
    build:
      context: .
      dockerfile: Services/Ordering/ordering-backgroundtasks/Dockerfile
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    networks:
      - simpbridgenetwork
  webspa:
    build:
      context: .
      dockerfile: Web/WebSpa/server/Dockerfile  
    ports:
    - 8080:8080
    networks:
    - simpbridgenetwork

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin 
    - DB_VENDOR=h2
    - KC_HEALTH_ENABLED=true
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./Keycloak:/opt/keycloak/data/import
    command: -v start-dev --import-realm
    ports:
    - 8095:8080
    networks:
    - simpbridgenetwork
  
  webshoppingapigw:
    image: envoyproxy/envoy:v1.11.1
    networks:
    - simpbridgenetwork

  basketdata:
    image: redis:alpine
    networks:
    - simpbridgenetwork
  
  webhooks-api:    
    build:
      context: .
      dockerfile: Services/Webhooks/webhooks-api/Dockerfile
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      eventbus:
        condition: service_healthy
    ports:
    - 5113:8080
    networks:
    - simpbridgenetwork
  webhooks-client:    
    build:
      context: .
      dockerfile: Services/Webhooks/webhooks-client/Dockerfile
    env_file:
    - .env
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
    - 5114:8080
    networks:
    - simpbridgenetwork
  payment-api:
    build:
      context: .
      dockerfile: Services/Payment/paymentapi/Dockerfile
    env_file:
    - .env
    depends_on:      
      eventbus:
        condition: service_healthy
    ports:
    - 5108:8080
    networks:
    - simpbridgenetwork

  # using Dockerfile filebeat to get around the file permission issue
  filebeat:
    build:
      context: .
      dockerfile: EFK/Dockerfile
    volumes:
      # - ./EFK/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - applog_volume:/app/logs
    networks:
    - simpbridgenetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
    - simpbridgenetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
    - simpbridgenetwork

volumes:
  applog_volume:
  esdata:

networks:
  simpbridgenetwork:
