services:
  webshoppingapigw:
    volumes:
    - ./Gateways/Envoy/config/webshopping:/etc/envoy
    ports:
    - "8090:80"
    - "8091:8001"
  catalog-api:
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/catalog-api"
  basket-api:
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/basket-api"
  ordering-api:
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/ordering-api"
  basketdata:
    ports:
    - "6379:6379"
  ordering-backgroundtasks:
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/ordering-backgroundtasks"
  webhooks-api:
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/webhooks-api"
  webhooks-client:
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/webhooks-client"

  
