spring:
    datasource:
        url: jdbc:sqlserver://localhost:1433;databaseName=CatalogDB;createDatabaseIfNotExist=true
        username: sa
        password: Pass@word
    jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    jpa.hibernate.ddl-auto: update
    jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
