spring:
  application:
    name: catalog-api
  profiles:
    active:
    - dev
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      naming.implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"

  #enable management endpoints
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server: 
            requests: true
  tracing:
    sampling:
      probability: 1.0
        
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

allowedCorsOrigin: "*"