spring:
    datasource:
        url: jdbc:sqlserver://host.docker.internal:1433;databaseName=CatalogDB;createDatabaseIfNotExist=true
        username: sa
        password: Pass@word
    jpa.properties.hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    jpa.hibernate.ddl-auto: update
    jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port: 80
picBaseUrl: "http://host.docker.internal:5202/catalog-api/api/v1/catalog/items/[0]/pic/"
springdoc.swagger-ui.path: /swagger-ui-custom.html
