spring:
  datasource:    
    url: ${catalog.datasource.url}
    username: ${catalog.datasource.username}
    password: ${catalog.datasource.password}
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      naming.implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"

picBaseUrl: ${catalog.picBaseUrl}
eventbus:
  host: ${eventbus.Host}
  username: ${eventbus.username}
  password: ${eventbus.password}
  retryCount: ${eventbus.retryCount}

springdoc.swagger-ui.path: /swagger-ui-custom.html
