spring:
  application:
    name: catalog-api
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      naming.implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
