spring:
  # cloud:
  #   vault:
  #     token: myroot
  #     uri: http://vault:8200
  #     kv:
  #       enabled: true
  #       backend: secret
  #       profile-separator: "/"
  #       application-name: catalog-api
  datasource:    
    url: ${catalog.datasource.url}
    username: ${catalog.datasource.username}
    password: ${catalog.datasource.password}
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    hibernate:
      ddl-auto: update
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      naming.implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"

allowedCorsOrigin: ${webspa.allowedCorsOrigin}

eventbus:
  host: ${eventbus.host}
  username: ${eventbus.username}
  password: ${eventbus.password}
  retryCount: ${eventbus.retryCount}
  subscriptionClientName: "Catalog"

springdoc.swagger-ui.path: /swagger-ui-custom.html

logging:
  level:
    com.eshoponcontainers: DEBUG
