spring:
  application:
    name: ordering-api
  profiles:
    active:
    - dev

logging:
  level:
    org.springframework.security.oauth2.jwt: DEBUG
    org.hibernate.type: TRACE

  #enable management endpoints
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server: 
            requests: true
  tracing:
    sampling:
      probability: 1.0
        
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

spring.datasource.hikari:
  maximum-pool-size: 10
  minimum-idle: 5
  connection-timeout: 30000
  idle-timeout: 600000
  max-lifetime: 1800000
  pool-name: HikariCP
  validation-timeout: 3000
  leak-detection-threshold: 2000