order:
  datasource:    
    url: ${orderapi.datasource.url}
    username: ${orderapi.datasource.username}
    password: ${orderapi.datasource.password}

eventbus:
  host: ${eventbus.host}
  username: ${eventbus.username}
  password: ${eventbus.password}
  retryCount: ${eventbus.retryCount}
  subscriptionClientName: "Ordering"

oauthIssuerUrl: ${issuer.url}

logging:
  level:
    com.eshoponcontainers: DEBUG