replicaCount: 1

image:
  repository: harshaghanta/db
  pullPolicy: Always
  tag: "latest"

sql:
  common:
    pid: "Developer"
    pwd: "P@ssw0rd"

ingress:
  enabled: true

service:
  type: ClusterIP
  port: 1433

  name: sql-service
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
