replicaCount: 1

image:
  repository: harshaghanta/db
  pullPolicy: Never
  tag: "latest"

ingress:
  enabled: true

service:
  type: ClusterIP
  internalPort: 1433
  externalPort: 9433
  name: sql-service
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
