replicaCount: 1

image:
  repository: harshaghanta/orderingbackgroundtasks
  pullPolicy: Always
  tag: "latest"

fluentbit:
  enabled: false
  indexName: ordering-backgroundtasks-logs
  logPath: /app/logs
  image:
    repository: fluent/fluent-bit
    tag: 1.8.3
    pullPolicy: IfNotPresent
  elasticsearch:
    host: "elasticsearch-master.logging.svc.cluster.local"
    port: 9200
    user: "elastic"
    password: "elastic"

eventbus:
  svc: rabbitmq
  user: "guest"
  pwd: "guest"
  retryCount: "5"

sql:
  common:
    user: "sa"
    pwd: "P@ssw0rd"
  datasource:
    url: "jdbc:sqlserver://sql-data:1433;databaseName=OrderDB;integratedSecurity=false;encrypt=false;trustServerCertificate=true;"


env:
  configmap:
  - name: "eventbus.host"
    key: eventbus__host
  - name: "eventbus.username"
    key: eventbus__username
  - name: "eventbus.password"
    key: eventbus__password  
  - name: "orderapi.datasource.url"
    key: ordering__dataSourceUrl
  - name: "orderapi.datasource.username"
    key: ordering__dataSourceUsername
  - name: "orderapi.datasource.password"
    key: ordering__dataSourcePassword



resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 10
    periodSeconds: 15
    port: 80
  readiness:
    path: /hc
    timeoutSeconds: 5
    initialDelaySeconds: 90
    periodSeconds: 60
    port: 80
