name: Catalog API Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Change to Java 17 version
        distribution: 'temurin' # Use AdoptOpenJDK 1.3 as the distribution


    - name: run maven build
      run: mvn clean install
     
    - name: Print directory structure
      run: ls -R

    # - name: Build catalog-api
    #   run: |
    #     cd catalog-api
    #     mvn clean install # Use Maven as the build command