name: Catalog API Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/catalogapi/**
    - .github/workflows/catalog-api.yml

env:
  SERVICE: catalog-api
  IMAGE: catalogapi

jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
                  
    - name: Frogbot by JFrog              
      uses: jfrog/frogbot@v2.21.11

    - name: Build & publish docker images
      uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ secrets.REGISTRY_HOST }}        
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.DOCKER_USERNAME }}
        registry_password: ${{ secrets.DOCKER_PASSWORD }}
        registry_namespace: ${{ secrets.DOCKER_NAMESPACE }}

   