name: "Build and publish eventbus to github packages"
on:
  workflow_dispatch:
  push:
    branches:
      - main

    paths:
    - src/BuildingBlocks/EventBus/eventbus/**
    - .github/workflows/eventbus-publish.yml

jobs:
  BuildEventBus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: |
          [
            {
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GIT_TOKEN }}"
            }
          ]
    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Unit Tests
      run: mvn -B test -f src/BuildingBlocks/EventBus/eventbus/pom.xml

    - name: Build & Package
      run: mvn -B package -f src/BuildingBlocks/EventBus/eventbus/pom.xml

    - name: Publish to GitHub Packages
      run: mvn -B deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ secrets.GIT_USERNAME }}/springboot-eshopOnContainers -f src/BuildingBlocks/EventBus/eventbus/pom.xml

