name: Order API Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

    paths:
    - src/BuildingBlocks/**
    - src/Services/Ordering/orderapi/**
    - src/Services/Ordering/ordering-domain/**
    - src/Services/Ordering/ordering-infrastructure/**
    - .github/workflows/ordering-api.yml

env:
  SERVICE: ordering-api
  IMAGE: orderingapi

jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build & publish docker images
      uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ secrets.REGISTRY_HOST }}        
        registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ secrets.DOCKER_USERNAME }}
        registry_password: ${{ secrets.DOCKER_PASSWORD }}

   